import type { DemoDatabase } from "@/types";

const NOW = "2026-09-01T12:00:00.000Z";
const EARLIER = "2026-06-15T12:00:00.000Z";

/**
 * DEMO seed — clearly fictional data for UI validation only.
 * Does not represent real CAIXA Consórcio features in production.
 */
export const demoDatabase: DemoDatabase = {
  products: [
    {
      id: "imobiliario",
      name: "Imobiliário",
      shortName: "Imobiliário",
      description:
        "Crédito para imóvel residencial ou comercial, terreno e construção.",
      order: 1,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "veiculos_leves",
      name: "Veículos leves",
      shortName: "Veículos leves",
      description:
        "Automóveis, utilitários leves e motocicletas para pessoa física e jurídica.",
      order: 2,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "veiculos_pesados",
      name: "Veículos pesados",
      shortName: "Veículos pesados",
      description:
        "Caminhões, ônibus, máquinas e equipamentos para operações empresariais.",
      order: 3,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  audiences: [
    {
      id: "aud-client",
      code: "CLIENT",
      name: "Cliente",
      description: "Pessoa física ou jurídica titular de cota de consórcio.",
      active: true,
    },
    {
      id: "aud-economiario",
      code: "ECONOMIARIO",
      name: "Economiário",
      description: "Colaborador da CAIXA que atende e opera consórcio.",
      active: true,
    },
    {
      id: "aud-partner",
      code: "PARTNER",
      name: "Parceiro",
      description: "Parceiro comercial (extrarede) que vende e acompanha consórcio.",
      active: true,
    },
  ],

  moments: [
    {
      id: "mom-sale",
      code: "SALE",
      name: "Venda",
      description: "Jornada de aquisição e contratação.",
      active: true,
    },
    {
      id: "mom-after-sale",
      code: "AFTER_SALE",
      name: "Pós-venda",
      description: "Jornada de acompanhamento e gestão da cota.",
      active: true,
    },
  ],

  channels: [
    {
      id: "ch-autocompra",
      name: "Autocompra",
      description: "Canal digital de autocompra para Cliente na Venda.",
      type: "digital",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-ibc",
      name: "IBC",
      description: "Internet Banking CAIXA — venda para Cliente.",
      type: "digital",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-app-consorcio",
      name: "App atual CAIXA Consórcio",
      description: "Aplicativo dedicado de pós-venda do Consórcio.",
      type: "app",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-app-caixa",
      name: "App CAIXA",
      description: "Aplicativo institucional CAIXA com serviços de consórcio.",
      type: "app",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-area-logada",
      name: "Área logada",
      description: "Área logada web de pós-venda para Cliente.",
      type: "web",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-superapp",
      name: "SuperApp",
      description: "Canal futuro unificado para Cliente (Venda e Pós-venda).",
      type: "app",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-aic",
      name: "AIC",
      description: "Ambiente interno de contratação para Economiário.",
      type: "internal",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-portal",
      name: "Portal do Consórcio",
      description: "Portal operacional de pós-venda (Economiário) e referência futura (Parceiro).",
      type: "portal",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-plataforma",
      name: "Plataforma.CAIXA",
      description: "Canal futuro unificado para Economiário (Venda e Pós-venda).",
      type: "platform",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-aic-extrarede",
      name: "AIC Extrarede",
      description: "Ambiente de contratação para Parceiro na Venda.",
      type: "partner",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  /** Official channel matrix — Público × Momento × Canal × Situação */
  channelContexts: [
    // Cliente — Venda
    {
      id: "cc-cli-sale-autocompra",
      audienceId: "aud-client",
      momentId: "mom-sale",
      channelId: "ch-autocompra",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-cli-sale-ibc",
      audienceId: "aud-client",
      momentId: "mom-sale",
      channelId: "ch-ibc",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-cli-sale-superapp",
      audienceId: "aud-client",
      momentId: "mom-sale",
      channelId: "ch-superapp",
      temporalStatus: "FUTURE",
      notes: "Canal futuro de venda para Cliente.",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Cliente — Pós-venda
    {
      id: "cc-cli-as-app-consorcio",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      channelId: "ch-app-consorcio",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-cli-as-app-caixa",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      channelId: "ch-app-caixa",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-cli-as-area-logada",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      channelId: "ch-area-logada",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-cli-as-superapp",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      channelId: "ch-superapp",
      temporalStatus: "FUTURE",
      notes: "Canal futuro de pós-venda para Cliente.",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Economiário — Venda
    {
      id: "cc-eco-sale-aic",
      audienceId: "aud-economiario",
      momentId: "mom-sale",
      channelId: "ch-aic",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-eco-sale-plataforma",
      audienceId: "aud-economiario",
      momentId: "mom-sale",
      channelId: "ch-plataforma",
      temporalStatus: "FUTURE",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Economiário — Pós-venda
    {
      id: "cc-eco-as-portal",
      audienceId: "aud-economiario",
      momentId: "mom-after-sale",
      channelId: "ch-portal",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-eco-as-plataforma",
      audienceId: "aud-economiario",
      momentId: "mom-after-sale",
      channelId: "ch-plataforma",
      temporalStatus: "FUTURE",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Parceiro — Venda
    {
      id: "cc-par-sale-aic-extra",
      audienceId: "aud-partner",
      momentId: "mom-sale",
      channelId: "ch-aic-extrarede",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-par-sale-portal",
      audienceId: "aud-partner",
      momentId: "mom-sale",
      channelId: "ch-portal",
      temporalStatus: "FUTURE",
      notes: "Evolução do Portal para atender Venda do Parceiro.",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Parceiro — Pós-venda
    {
      id: "cc-par-as-portal",
      audienceId: "aud-partner",
      momentId: "mom-after-sale",
      channelId: "ch-portal",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  /** Fase 15.6 — apenas a Journey canônica ativa. Sem jornadas legado/demo. */
  journeys: [
    {
      id: "jrn-consorcio",
      name: "Jornada do Consórcio",
      description:
        "Jornada compartilhada do consórcio CAIXA — da descoberta ao encerramento. As etapas são JourneyStages; públicos compartilham a mesma estrutura.",
      order: 1,
      momentIds: ["mom-sale", "mom-after-sale"],
      productIds: [],
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  journeyStages: [
    {
      id: "js-jrn-descoberta",
      journeyId: "jrn-consorcio",
      name: "Descoberta",
      description: "Conhecer o consórcio",
      order: 1,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "js-jrn-consideracao",
      journeyId: "jrn-consorcio",
      name: "Consideração",
      description: "Avaliar e comparar",
      order: 2,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "js-jrn-contratacao",
      journeyId: "jrn-consorcio",
      name: "Contratação",
      description: "Adquirir o consórcio",
      order: 3,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "js-jrn-onboarding",
      journeyId: "jrn-consorcio",
      name: "Onboarding",
      description: "Pós-compra inicial",
      order: 4,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "js-jrn-acompanhamento",
      journeyId: "jrn-consorcio",
      name: "Acompanhamento",
      description: "Gerenciar minha cota",
      order: 5,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "js-jrn-lance",
      journeyId: "jrn-consorcio",
      name: "Lance",
      description: "Aumentar as chances de contemplação por meio de ofertas de lance.",
      order: 6,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "js-jrn-contemplacao",
      journeyId: "jrn-consorcio",
      name: "Contemplação",
      description: "Acompanhar resultado e próximos passos da contemplação.",
      order: 7,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "js-jrn-uso-credito",
      journeyId: "jrn-consorcio",
      name: "Uso do crédito",
      description: "Utilizar o crédito",
      order: 8,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "js-jrn-pos-uso",
      journeyId: "jrn-consorcio",
      name: "Pós-uso",
      description: "Após utilizar",
      order: 9,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "js-jrn-encerramento",
      journeyId: "jrn-consorcio",
      name: "Encerramento",
      description: "Finalizar o plano",
      order: 10,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  journeyAudienceStages: [
    {
      id: "jas-cli-descoberta",
      audienceId: "aud-client",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-descoberta",
      displayName: "Descoberta",
      sortOrder: 1,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-consideracao",
      audienceId: "aud-client",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-consideracao",
      displayName: "Consideração",
      sortOrder: 2,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-contratacao",
      audienceId: "aud-client",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-contratacao",
      displayName: "Contratação",
      sortOrder: 3,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-onboarding",
      audienceId: "aud-client",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-onboarding",
      displayName: "Onboarding",
      sortOrder: 4,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-acompanhamento",
      audienceId: "aud-client",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-acompanhamento",
      displayName: "Acompanhamento",
      sortOrder: 5,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-lance",
      audienceId: "aud-client",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-lance",
      displayName: "Lance",
      sortOrder: 6,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-contemplacao",
      audienceId: "aud-client",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-contemplacao",
      displayName: "Contemplação",
      sortOrder: 7,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-uso-credito",
      audienceId: "aud-client",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-uso-credito",
      displayName: "Uso do crédito",
      sortOrder: 8,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-pos-uso",
      audienceId: "aud-client",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-pos-uso",
      displayName: "Pós-uso",
      sortOrder: 9,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-encerramento",
      audienceId: "aud-client",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-encerramento",
      displayName: "Encerramento",
      sortOrder: 10,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-descoberta",
      audienceId: "aud-economiario",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-descoberta",
      displayName: "Descoberta",
      sortOrder: 1,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-consideracao",
      audienceId: "aud-economiario",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-consideracao",
      displayName: "Consideração",
      sortOrder: 2,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-contratacao",
      audienceId: "aud-economiario",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-contratacao",
      displayName: "Venda",
      sortOrder: 3,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-onboarding",
      audienceId: "aud-economiario",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-onboarding",
      displayName: "Onboarding",
      sortOrder: 4,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-acompanhamento",
      audienceId: "aud-economiario",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-acompanhamento",
      displayName: "Acompanhamento",
      sortOrder: 5,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-lance",
      audienceId: "aud-economiario",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-lance",
      displayName: "Lance",
      sortOrder: 6,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-contemplacao",
      audienceId: "aud-economiario",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-contemplacao",
      displayName: "Contemplação",
      sortOrder: 7,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-uso-credito",
      audienceId: "aud-economiario",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-uso-credito",
      displayName: "Uso do crédito",
      sortOrder: 8,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-pos-uso",
      audienceId: "aud-economiario",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-pos-uso",
      displayName: "Pós-uso",
      sortOrder: 9,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-encerramento",
      audienceId: "aud-economiario",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-encerramento",
      displayName: "Encerramento",
      sortOrder: 10,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-descoberta",
      audienceId: "aud-partner",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-descoberta",
      displayName: "Descoberta",
      sortOrder: 1,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-consideracao",
      audienceId: "aud-partner",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-consideracao",
      displayName: "Consideração",
      sortOrder: 2,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-contratacao",
      audienceId: "aud-partner",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-contratacao",
      displayName: "Venda",
      sortOrder: 3,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-onboarding",
      audienceId: "aud-partner",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-onboarding",
      displayName: "Onboarding",
      sortOrder: 4,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-acompanhamento",
      audienceId: "aud-partner",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-acompanhamento",
      displayName: "Acompanhamento",
      sortOrder: 5,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-lance",
      audienceId: "aud-partner",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-lance",
      displayName: "Lance",
      sortOrder: 6,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-contemplacao",
      audienceId: "aud-partner",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-contemplacao",
      displayName: "Contemplação",
      sortOrder: 7,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-uso-credito",
      audienceId: "aud-partner",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-uso-credito",
      displayName: "Uso do crédito",
      sortOrder: 8,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-pos-uso",
      audienceId: "aud-partner",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-pos-uso",
      displayName: "Pós-uso",
      sortOrder: 9,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-encerramento",
      audienceId: "aud-partner",
      journeyId: "jrn-consorcio",
      journeyStageId: "js-jrn-encerramento",
      displayName: "Encerramento",
      sortOrder: 10,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  /** Fase 15.6 — catálogo vazio; população real em fase posterior. */
  userNeeds: [],

  capabilities: [],

  features: [],

  featureNeeds: [],

  featureJourneys: [],

  featureUserProfiles: [],

  featureChannelContexts: [],

  evidences: [],

  roadmapPhases: [
    {
      id: "rph-backlog",
      code: "BACKLOG",
      name: "Backlog",
      symbol: "◌",
      sortOrder: 1,
      active: false,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-ux-ui",
      code: "UX_UI",
      name: "UX/UI",
      symbol: "◐",
      sortOrder: 2,
      active: false,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-dev",
      code: "DEVELOPMENT",
      name: "Em desenvolvimento",
      symbol: "◐",
      sortOrder: 3,
      active: false,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-homolog",
      code: "HOMOLOGATION",
      name: "Homologação",
      symbol: "◐",
      sortOrder: 4,
      active: false,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-paused",
      code: "PAUSED",
      name: "Pausado",
      symbol: "Ⅱ",
      sortOrder: 5,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-removed",
      code: "REMOVED",
      name: "Removido",
      symbol: "",
      sortOrder: 6,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-available",
      code: "AVAILABLE",
      name: "Disponível",
      symbol: "●",
      sortOrder: 7,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  /**
   * @deprecated Fase 6 — LEGADO. Não criar novos itens.
   * Equivalentes já existem em featureChannelContexts (Implementation).
   * Mantido para compatibilidade/leitura até remoção da tabela.
   * rm-1 ↔ fcc-cota-superapp · rm-2 ↔ fcc-lance-superapp ·
   * rm-3 ↔ fcc-sim-plataforma · rm-4 ↔ fcc-assist-plataforma
   */
  roadmapItems: [],

  gaps: [],

  featureEvolutions: [],

  featureChannelEvaluations: [],
};
