import type { DemoDatabase } from "@/types";

const NOW = "2026-09-01T12:00:00.000Z";
const EARLIER = "2026-06-15T12:00:00.000Z";

/**
 * DEMO seed — clearly fictional data for UI validation only.
 * Does not represent real CAIXA Consórcio features in production.
 */
export const demoDatabase: DemoDatabase = {
  products: [
    {
      id: "imobiliario",
      name: "Imobiliário",
      shortName: "Imobiliário",
      description:
        "Crédito para imóvel residencial ou comercial, terreno e construção.",
      order: 1,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "veiculos_leves",
      name: "Veículos Leves",
      shortName: "Veículos Leves",
      description:
        "Automóveis, utilitários leves e motocicletas para pessoa física e jurídica.",
      order: 2,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "veiculos_pesados",
      name: "Veículos Pesados",
      shortName: "Veículos Pesados",
      description:
        "Caminhões, ônibus, máquinas e equipamentos para operações empresariais.",
      order: 3,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  audiences: [
    {
      id: "aud-client",
      code: "CLIENT",
      name: "Cliente",
      description: "Pessoa física ou jurídica titular de cota de consórcio.",
      active: true,
    },
    {
      id: "aud-economiario",
      code: "ECONOMIARIO",
      name: "Economiário",
      description: "Colaborador da CAIXA que atende e opera consórcio.",
      active: true,
    },
    {
      id: "aud-partner",
      code: "PARTNER",
      name: "Parceiro",
      description: "Parceiro comercial (extrarede) que vende e acompanha consórcio.",
      active: true,
    },
  ],

  moments: [
    {
      id: "mom-sale",
      code: "SALE",
      name: "Venda",
      description: "Jornada de aquisição e contratação.",
      active: true,
    },
    {
      id: "mom-after-sale",
      code: "AFTER_SALE",
      name: "Pós-venda",
      description: "Jornada de acompanhamento e gestão da cota.",
      active: true,
    },
  ],

  channels: [
    {
      id: "ch-autocompra",
      name: "Autocompra",
      description: "Canal digital de autocompra para Cliente na Venda.",
      type: "digital",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-ibc",
      name: "IBC",
      description: "Internet Banking CAIXA — venda para Cliente.",
      type: "digital",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-app-consorcio",
      name: "App atual CAIXA Consórcio",
      description: "Aplicativo dedicado de pós-venda do Consórcio.",
      type: "app",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-app-caixa",
      name: "App CAIXA",
      description: "Aplicativo institucional CAIXA com serviços de consórcio.",
      type: "app",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-area-logada",
      name: "Área logada",
      description: "Área logada web de pós-venda para Cliente.",
      type: "web",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-superapp",
      name: "SuperApp CAIXA",
      description: "Canal futuro unificado para Cliente (Venda e Pós-venda).",
      type: "app",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-aic",
      name: "AIC",
      description: "Ambiente interno de contratação para Economiário.",
      type: "internal",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-portal",
      name: "Portal do Consórcio",
      description: "Portal operacional de pós-venda (Economiário) e referência futura (Parceiro).",
      type: "portal",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-plataforma",
      name: "Plataforma.CAIXA",
      description: "Canal futuro unificado para Economiário (Venda e Pós-venda).",
      type: "platform",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "ch-aic-extrarede",
      name: "AIC Extrarede",
      description: "Ambiente de contratação para Parceiro na Venda.",
      type: "partner",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  /** Official channel matrix — Público × Momento × Canal × Situação */
  channelContexts: [
    // Cliente — Venda
    {
      id: "cc-cli-sale-autocompra",
      audienceId: "aud-client",
      momentId: "mom-sale",
      channelId: "ch-autocompra",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-cli-sale-ibc",
      audienceId: "aud-client",
      momentId: "mom-sale",
      channelId: "ch-ibc",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-cli-sale-superapp",
      audienceId: "aud-client",
      momentId: "mom-sale",
      channelId: "ch-superapp",
      temporalStatus: "FUTURE",
      notes: "Canal futuro de venda para Cliente.",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Cliente — Pós-venda
    {
      id: "cc-cli-as-app-consorcio",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      channelId: "ch-app-consorcio",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-cli-as-app-caixa",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      channelId: "ch-app-caixa",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-cli-as-area-logada",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      channelId: "ch-area-logada",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-cli-as-superapp",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      channelId: "ch-superapp",
      temporalStatus: "FUTURE",
      notes: "Canal futuro de pós-venda para Cliente.",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Economiário — Venda
    {
      id: "cc-eco-sale-aic",
      audienceId: "aud-economiario",
      momentId: "mom-sale",
      channelId: "ch-aic",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-eco-sale-plataforma",
      audienceId: "aud-economiario",
      momentId: "mom-sale",
      channelId: "ch-plataforma",
      temporalStatus: "FUTURE",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Economiário — Pós-venda
    {
      id: "cc-eco-as-portal",
      audienceId: "aud-economiario",
      momentId: "mom-after-sale",
      channelId: "ch-portal",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-eco-as-plataforma",
      audienceId: "aud-economiario",
      momentId: "mom-after-sale",
      channelId: "ch-plataforma",
      temporalStatus: "FUTURE",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Parceiro — Venda
    {
      id: "cc-par-sale-aic-extra",
      audienceId: "aud-partner",
      momentId: "mom-sale",
      channelId: "ch-aic-extrarede",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cc-par-sale-portal",
      audienceId: "aud-partner",
      momentId: "mom-sale",
      channelId: "ch-portal",
      temporalStatus: "FUTURE",
      notes: "Evolução do Portal para atender Venda do Parceiro.",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Parceiro — Pós-venda
    {
      id: "cc-par-as-portal",
      audienceId: "aud-partner",
      momentId: "mom-after-sale",
      channelId: "ch-portal",
      temporalStatus: "CURRENT",
      notes: "",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  journeys: [
    {
      id: "jrn-descoberta",
      name: "Descoberta",
      description: "Conhecer o consórcio",
      order: 1,
      momentIds: ["mom-sale"],
      productIds: [],
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jrn-consideracao",
      name: "Consideração",
      description: "Avaliar e comparar",
      order: 2,
      momentIds: ["mom-sale"],
      productIds: [],
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jrn-contratacao",
      name: "Contratação",
      description: "Adquirir o consórcio",
      order: 3,
      momentIds: ["mom-sale"],
      productIds: [],
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jrn-onboarding",
      name: "Onboarding",
      description: "Pós-compra inicial",
      order: 4,
      momentIds: ["mom-after-sale"],
      productIds: [],
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jrn-acompanhamento",
      name: "Acompanhamento",
      description: "Gerenciar minha cota",
      order: 5,
      momentIds: ["mom-after-sale"],
      productIds: [],
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jrn-lance",
      name: "Lance",
      description: "Aumentar chance",
      order: 6,
      momentIds: ["mom-after-sale"],
      productIds: [],
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jrn-contemplacao",
      name: "Contemplação",
      description: "Receber o crédito",
      order: 7,
      momentIds: ["mom-after-sale"],
      productIds: [],
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jrn-uso-credito",
      name: "Uso do crédito",
      description: "Utilizar o crédito",
      order: 8,
      momentIds: ["mom-after-sale"],
      productIds: [],
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jrn-pos-uso",
      name: "Pós-uso",
      description: "Após utilizar",
      order: 9,
      momentIds: ["mom-after-sale"],
      productIds: [],
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jrn-encerramento",
      name: "Encerramento",
      description: "Finalizar o plano",
      order: 10,
      momentIds: ["mom-after-sale"],
      productIds: [],
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jrn-financeiro",
      name: "Financeiro",
      description: "Pagar parcelas, emitir boletos e consultar extrato.",
      order: 99,
      momentIds: ["mom-after-sale"],
      productIds: [],
      active: false,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  journeyAudienceStages: [
    // Cliente — jornada completa
    {
      id: "jas-cli-descoberta",
      audienceId: "aud-client",
      journeyId: "jrn-descoberta",
      displayName: "Descoberta",
      sortOrder: 1,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-consideracao",
      audienceId: "aud-client",
      journeyId: "jrn-consideracao",
      displayName: "Consideração",
      sortOrder: 2,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-contratacao",
      audienceId: "aud-client",
      journeyId: "jrn-contratacao",
      displayName: "Contratação",
      sortOrder: 3,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-onboarding",
      audienceId: "aud-client",
      journeyId: "jrn-onboarding",
      displayName: "Onboarding",
      sortOrder: 4,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-acompanhamento",
      audienceId: "aud-client",
      journeyId: "jrn-acompanhamento",
      displayName: "Acompanhamento",
      sortOrder: 5,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-lance",
      audienceId: "aud-client",
      journeyId: "jrn-lance",
      displayName: "Lance",
      sortOrder: 6,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-contemplacao",
      audienceId: "aud-client",
      journeyId: "jrn-contemplacao",
      displayName: "Contemplação",
      sortOrder: 7,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-uso-credito",
      audienceId: "aud-client",
      journeyId: "jrn-uso-credito",
      displayName: "Uso do crédito",
      sortOrder: 8,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-pos-uso",
      audienceId: "aud-client",
      journeyId: "jrn-pos-uso",
      displayName: "Pós-uso",
      sortOrder: 9,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-cli-encerramento",
      audienceId: "aud-client",
      journeyId: "jrn-encerramento",
      displayName: "Encerramento",
      sortOrder: 10,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Economiário — venda (mesmo catálogo da contratação do cliente)
    {
      id: "jas-eco-venda",
      audienceId: "aud-economiario",
      journeyId: "jrn-contratacao",
      displayName: "Venda",
      sortOrder: 1,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-acompanhamento",
      audienceId: "aud-economiario",
      journeyId: "jrn-acompanhamento",
      displayName: "Acompanhamento",
      sortOrder: 2,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-lance",
      audienceId: "aud-economiario",
      journeyId: "jrn-lance",
      displayName: "Lance",
      sortOrder: 3,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-eco-contemplacao",
      audienceId: "aud-economiario",
      journeyId: "jrn-contemplacao",
      displayName: "Contemplação",
      sortOrder: 4,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    // Parceiro
    {
      id: "jas-par-venda",
      audienceId: "aud-partner",
      journeyId: "jrn-contratacao",
      displayName: "Venda",
      sortOrder: 1,
      momentId: "mom-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-acompanhamento",
      audienceId: "aud-partner",
      journeyId: "jrn-acompanhamento",
      displayName: "Acompanhamento",
      sortOrder: 2,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-lance",
      audienceId: "aud-partner",
      journeyId: "jrn-lance",
      displayName: "Lance",
      sortOrder: 3,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "jas-par-contemplacao",
      audienceId: "aud-partner",
      journeyId: "jrn-contemplacao",
      displayName: "Contemplação",
      sortOrder: 4,
      momentId: "mom-after-sale",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  userNeeds: [
    {
      id: "need-conhecer",
      journeyId: "jrn-descoberta",
      name: "Conhecer produtos de consórcio",
      description: "Entender modalidades, prazos e valores disponíveis.",
      priority: "HIGH",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "need-simular",
      journeyId: "jrn-contratacao",
      name: "Simular e contratar consórcio",
      description: "Realizar simulação e concluir a contratação.",
      priority: "CRITICAL",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "need-acompanhar-cota",
      journeyId: "jrn-acompanhamento",
      name: "Quero saber como está minha cota",
      description: "Ver situação, saldo e progresso da cota.",
      priority: "CRITICAL",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "need-pagar",
      journeyId: "jrn-acompanhamento",
      name: "Quero pagar minhas parcelas",
      description: "Emitir boleto e quitar parcelas em dia.",
      priority: "CRITICAL",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "need-assembleias",
      journeyId: "jrn-acompanhamento",
      name: "Quero acompanhar as assembleias",
      description: "Ver próximas assembleias e resultados.",
      priority: "HIGH",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "need-documentos",
      journeyId: "jrn-acompanhamento",
      name: "Quero ver meus documentos",
      description: "Consultar contratos e documentos da cota.",
      priority: "MEDIUM",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "need-historico-financeiro",
      journeyId: "jrn-acompanhamento",
      name: "Quero entender meu histórico financeiro",
      description: "Consultar pagamentos e extratos.",
      priority: "HIGH",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "need-atualizar-dados",
      journeyId: "jrn-acompanhamento",
      name: "Quero atualizar meus dados",
      description: "Atualizar dados cadastrais e de cobrança.",
      priority: "MEDIUM",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "need-lance",
      journeyId: "jrn-lance",
      name: "Ofertar lance",
      description: "Registrar e acompanhar oferta de lance.",
      priority: "HIGH",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "need-contemplacao",
      journeyId: "jrn-contemplacao",
      name: "Acompanhar contemplação",
      description: "Saber se foi contemplado e próximos passos.",
      priority: "HIGH",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "need-atender-cliente",
      journeyId: "jrn-acompanhamento",
      name: "Atender consulta de cota do cliente",
      description: "Economiário/parceiro consulta cota em nome do cliente.",
      priority: "HIGH",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  capabilities: [
    {
      id: "cap-catalogo",
      userNeedId: "need-conhecer",
      name: "Consulta de catálogo de produtos",
      description: "Exibir e filtrar produtos de consórcio.",
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cap-simulacao",
      userNeedId: "need-simular",
      name: "Simulação e proposta",
      description: "Gerar simulação e iniciar contratação.",
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cap-consulta-cota",
      userNeedId: "need-acompanhar-cota",
      name: "Consulta de cota",
      description: "Visualizar dados e status da cota.",
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cap-boleto",
      userNeedId: "need-pagar",
      name: "Emissão de boleto",
      description: "Gerar boleto da parcela.",
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cap-lance",
      userNeedId: "need-lance",
      name: "Gestão de lance",
      description: "Registrar e consultar lances.",
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cap-contemplacao",
      userNeedId: "need-contemplacao",
      name: "Consulta de contemplação",
      description: "Informar resultado e próximos passos.",
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "cap-atendimento-cota",
      userNeedId: "need-atender-cliente",
      name: "Consulta assistida de cota",
      description: "Consulta operacional por matrícula/CPF.",
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  features: [
    {
      id: "feat-consultar-produtos",
      capabilityId: "cap-catalogo",
      name: "Consultar produtos",
      description:
        "[DEMO] Listar produtos de consórcio disponíveis com filtros básicos.",
      product: "Imobiliário",
      priority: "HIGH",
      owner: "Time Venda Digital",
      uxOwner: "Ana UX",
      cxOwner: "Bruno CX",
      productOwner: "Carla PO",
      active: true,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "feat-simular",
      capabilityId: "cap-simulacao",
      name: "Simular consórcio",
      description:
        "[DEMO] Simular valores, prazos e parcelas antes da contratação.",
      product: "Imobiliário",
      priority: "CRITICAL",
      owner: "Time Venda Digital",
      uxOwner: "Ana UX",
      cxOwner: "Bruno CX",
      productOwner: "Carla PO",
      active: true,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "feat-consultar-cota",
      capabilityId: "cap-consulta-cota",
      name: "Consultar situação da cota",
      description:
        "[DEMO] Visualizar status, saldo devedor, assembleias e progresso.",
      product: "Veículos Leves",
      priority: "CRITICAL",
      owner: "Time Pós-venda",
      uxOwner: "Diana UX",
      cxOwner: "Eduardo CX",
      productOwner: "Fernanda PO",
      active: true,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "feat-emitir-boleto",
      capabilityId: "cap-boleto",
      name: "Emitir boleto",
      description: "[DEMO] Gerar boleto da parcela corrente ou em atraso.",
      product: "Veículos Leves",
      priority: "CRITICAL",
      owner: "Time Pós-venda",
      uxOwner: "Diana UX",
      cxOwner: "Eduardo CX",
      productOwner: "Fernanda PO",
      active: true,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "feat-dar-lance",
      capabilityId: "cap-lance",
      name: "Dar lance",
      description: "[DEMO] Ofertar lance livre ou fixo na assembleia.",
      product: "Veículos Leves",
      priority: "HIGH",
      owner: "Time Pós-venda",
      uxOwner: "Diana UX",
      cxOwner: "Eduardo CX",
      productOwner: "Fernanda PO",
      active: true,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "feat-resultado-contemplacao",
      capabilityId: "cap-contemplacao",
      name: "Ver resultado da contemplação",
      description: "[DEMO] Consultar se a cota foi contemplada e orientações.",
      product: "Veículos Pesados",
      priority: "HIGH",
      owner: "Time Pós-venda",
      uxOwner: "Diana UX",
      cxOwner: "Eduardo CX",
      productOwner: "Fernanda PO",
      active: true,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "feat-consulta-assistida",
      capabilityId: "cap-atendimento-cota",
      name: "Consulta assistida de cota",
      description:
        "[DEMO] Consulta operacional de cota por CPF/matrícula no atendimento.",
      product: "Veículos Pesados",
      priority: "HIGH",
      owner: "Time Operações",
      uxOwner: "Gina UX",
      cxOwner: "Hugo CX",
      productOwner: "Iris PO",
      active: true,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "feat-segunda-via-extrato",
      capabilityId: "cap-boleto",
      name: "Segunda via de extrato",
      description: "[DEMO] Baixar extrato detalhado da cota.",
      product: "Veículos Pesados",
      priority: "MEDIUM",
      owner: "Time Pós-venda",
      uxOwner: "Diana UX",
      cxOwner: "Eduardo CX",
      productOwner: "Fernanda PO",
      active: true,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "feat-simular-auto",
      capabilityId: "cap-simulacao",
      name: "Simular consórcio de veículos leves",
      description:
        "[DEMO] Simular crédito para automóveis e utilitários leves.",
      product: "Veículos Leves",
      priority: "CRITICAL",
      owner: "Time Venda Digital",
      uxOwner: "Ana UX",
      cxOwner: "Bruno CX",
      productOwner: "Carla PO",
      active: false,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "feat-simular-pesados",
      capabilityId: "cap-simulacao",
      name: "Simular consórcio de veículos pesados",
      description:
        "[DEMO] Simular crédito para caminhões, ônibus e equipamentos.",
      product: "Veículos Pesados",
      priority: "HIGH",
      owner: "Time Venda Digital",
      uxOwner: "Ana UX",
      cxOwner: "Bruno CX",
      productOwner: "Carla PO",
      active: false,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "feat-consultar-cota-imob",
      capabilityId: "cap-consulta-cota",
      name: "Consultar cota imobiliária",
      description:
        "[DEMO] Acompanhar cota de imóvel, saldo e calendário de assembleias.",
      product: "Imobiliário",
      priority: "CRITICAL",
      owner: "Time Pós-venda",
      uxOwner: "Diana UX",
      cxOwner: "Eduardo CX",
      productOwner: "Fernanda PO",
      active: false,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "feat-emitir-boleto-imob",
      capabilityId: "cap-boleto",
      name: "Emitir boleto imobiliário",
      description: "[DEMO] Gerar boleto de parcela do consórcio imobiliário.",
      product: "Imobiliário",
      priority: "HIGH",
      owner: "Time Pós-venda",
      uxOwner: "Diana UX",
      cxOwner: "Eduardo CX",
      productOwner: "Fernanda PO",
      active: false,
      isDemo: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  featureChannelContexts: [
    // --- Consultar produtos (Cliente Venda) ---
    {
      id: "fcc-prod-autocompra",
      featureId: "feat-consultar-produtos",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-sale-autocompra",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2024-01-10",
      expectedDate: "2024-03-01",
      launchDate: "2024-03-15",
      responsible: "Carla PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-prod-ibc",
      featureId: "feat-consultar-produtos",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-sale-ibc",
      status: "ON_TRACK",
      experience: "NEEDS_IMPROVEMENT",
      phase: "AVAILABLE",
      startDate: "2023-06-01",
      expectedDate: "2023-09-01",
      launchDate: "2023-09-20",
      responsible: "Carla PO",
      notes: "DEMO — navegação confusa",
      updatedAt: NOW,
    },
    {
      id: "fcc-prod-superapp",
      featureId: "feat-consultar-produtos",
      productId: "imobiliario",
      channelContextId: "cc-cli-sale-superapp",
      status: "DELAYED",
      experience: "NOT_EVALUATED",
      phase: "UX_UI",
      startDate: "2025-03-01",
      expectedDate: "2025-07-01",
      launchDate: null,
      responsible: "Carla PO",
      notes: "DEMO — Imobiliário · SuperApp · Futuro",
      updatedAt: NOW,
    },
    {
      id: "fcc-prod-autocompra-pesados",
      featureId: "feat-consultar-produtos",
      productId: "veiculos_pesados",
      channelContextId: "cc-cli-sale-autocompra",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2024-03-01",
      expectedDate: "2024-06-01",
      launchDate: "2024-06-10",
      responsible: "Carla PO",
      notes: "DEMO — Veículos Pesados",
      updatedAt: NOW,
    },
    {
      id: "fcc-prod-ibc-pesados",
      featureId: "feat-consultar-produtos",
      productId: "veiculos_pesados",
      channelContextId: "cc-cli-sale-ibc",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "DEVELOPMENT",
      startDate: "2026-01-01",
      expectedDate: "2026-09-01",
      launchDate: null,
      responsible: "Carla PO",
      notes: "DEMO — gap de paridade vs Leves",
      updatedAt: NOW,
    },

    // --- Simular (Cliente Venda + Economiário + Parceiro) ---
    {
      id: "fcc-sim-autocompra",
      featureId: "feat-simular",
      productId: "imobiliario",
      channelContextId: "cc-cli-sale-autocompra",
      status: "ON_TRACK",
      experience: "GOOD",
      phase: "AVAILABLE",
      startDate: "2024-01-10",
      expectedDate: "2024-04-01",
      launchDate: "2024-04-10",
      responsible: "Carla PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-sim-ibc",
      featureId: "feat-simular",
      productId: "imobiliario",
      channelContextId: "cc-cli-sale-ibc",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2023-06-01",
      expectedDate: "2023-10-01",
      launchDate: "2023-10-15",
      responsible: "Carla PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-sim-superapp-sale",
      featureId: "feat-simular",
      productId: "imobiliario",
      channelContextId: "cc-cli-sale-superapp",
      status: "ON_TRACK",
      experience: "NOT_EVALUATED",
      phase: "UX_UI",
      startDate: "2026-08-01",
      expectedDate: "2027-02-01",
      launchDate: null,
      responsible: "Ana UX",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-sim-aic",
      featureId: "feat-simular",
      productId: "imobiliario",
      channelContextId: "cc-eco-sale-aic",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2022-01-01",
      expectedDate: "2022-06-01",
      launchDate: "2022-06-30",
      responsible: "Iris PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-sim-plataforma",
      featureId: "feat-simular",
      productId: "imobiliario",
      channelContextId: "cc-eco-sale-plataforma",
      status: "DELAYED",
      experience: "NOT_EVALUATED",
      phase: "DEVELOPMENT",
      startDate: "2025-05-01",
      expectedDate: "2025-08-01",
      launchDate: null,
      responsible: "Iris PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-sim-aic-extra",
      featureId: "feat-simular",
      productId: "imobiliario",
      channelContextId: "cc-par-sale-aic-extra",
      status: "ON_TRACK",
      experience: "NEEDS_IMPROVEMENT",
      phase: "AVAILABLE",
      startDate: "2022-03-01",
      expectedDate: "2022-08-01",
      launchDate: "2022-08-15",
      responsible: "Iris PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-sim-portal-par",
      featureId: "feat-simular",
      productId: "imobiliario",
      channelContextId: "cc-par-sale-portal",
      status: "ON_TRACK",
      experience: "NOT_EVALUATED",
      phase: "UX_UI",
      startDate: null,
      expectedDate: "2027-06-01",
      launchDate: null,
      responsible: "Iris PO",
      notes: "DEMO — Portal evoluído para venda parceiro",
      updatedAt: NOW,
    },

    // --- Consultar cota (Cliente Pós-venda) ---
    {
      id: "fcc-cota-app-consorcio",
      featureId: "feat-consultar-cota",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-app-consorcio",
      status: "ON_TRACK",
      experience: "GOOD",
      phase: "AVAILABLE",
      startDate: "2021-01-01",
      expectedDate: "2021-06-01",
      launchDate: "2021-06-15",
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-cota-app-caixa",
      featureId: "feat-consultar-cota",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-app-caixa",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2022-01-01",
      expectedDate: "2022-09-01",
      launchDate: "2022-09-20",
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-cota-area-logada",
      featureId: "feat-consultar-cota",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-area-logada",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2020-01-01",
      expectedDate: "2020-08-01",
      launchDate: "2020-08-10",
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-cota-superapp",
      featureId: "feat-consultar-cota",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-superapp",
      status: "ON_TRACK",
      experience: "NOT_EVALUATED",
      phase: "BACKLOG",
      startDate: "2026-09-01",
      expectedDate: "2027-04-01",
      launchDate: null,
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },

    // --- Emitir boleto ---
    {
      id: "fcc-bol-app-consorcio",
      featureId: "feat-emitir-boleto",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-app-consorcio",
      status: "ON_TRACK",
      experience: "GOOD",
      phase: "AVAILABLE",
      startDate: "2021-01-01",
      expectedDate: "2021-07-01",
      launchDate: "2021-07-15",
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-bol-app-caixa",
      featureId: "feat-emitir-boleto",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-app-caixa",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2022-03-01",
      expectedDate: "2022-10-01",
      launchDate: "2022-10-12",
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-bol-area-logada",
      featureId: "feat-emitir-boleto",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-area-logada",
      status: "ON_TRACK",
      experience: "NEEDS_IMPROVEMENT",
      phase: "AVAILABLE",
      startDate: "2020-01-01",
      expectedDate: "2020-09-01",
      launchDate: "2020-09-05",
      responsible: "Fernanda PO",
      notes: "DEMO — fluxo longo",
      updatedAt: NOW,
    },
    {
      id: "fcc-bol-superapp",
      featureId: "feat-emitir-boleto",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-superapp",
      status: "ON_TRACK",
      experience: "NOT_EVALUATED",
      phase: "BACKLOG",
      startDate: "2026-10-01",
      expectedDate: "2027-05-01",
      launchDate: null,
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },

    // --- Dar lance ---
    {
      id: "fcc-lance-app-consorcio",
      featureId: "feat-dar-lance",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-app-consorcio",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2021-06-01",
      expectedDate: "2021-12-01",
      launchDate: "2021-12-10",
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-lance-app-caixa",
      featureId: "feat-dar-lance",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-app-caixa",
      status: "ON_TRACK",
      experience: "NOT_EVALUATED",
      phase: "REMOVED",
      startDate: null,
      expectedDate: null,
      launchDate: null,
      responsible: "Fernanda PO",
      notes: "DEMO — gap de cobertura no App CAIXA",
      updatedAt: NOW,
    },
    {
      id: "fcc-lance-area-logada",
      featureId: "feat-dar-lance",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-area-logada",
      status: "ON_TRACK",
      experience: "CRITICAL",
      phase: "AVAILABLE",
      startDate: "2020-06-01",
      expectedDate: "2020-11-01",
      launchDate: "2020-11-20",
      responsible: "Fernanda PO",
      notes: "DEMO — muitos erros de validação",
      updatedAt: NOW,
    },
    {
      id: "fcc-lance-superapp",
      featureId: "feat-dar-lance",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-as-superapp",
      status: "ON_TRACK",
      experience: "NOT_EVALUATED",
      phase: "DEVELOPMENT",
      startDate: "2026-07-01",
      expectedDate: "2027-01-15",
      launchDate: null,
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },

    // --- Contemplação ---
    {
      id: "fcc-cont-app-consorcio",
      featureId: "feat-resultado-contemplacao",
      productId: "veiculos_pesados",
      channelContextId: "cc-cli-as-app-consorcio",
      status: "ON_TRACK",
      experience: "GOOD",
      phase: "AVAILABLE",
      startDate: "2021-08-01",
      expectedDate: "2022-01-01",
      launchDate: "2022-01-20",
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-cont-app-caixa",
      featureId: "feat-resultado-contemplacao",
      productId: "veiculos_pesados",
      channelContextId: "cc-cli-as-app-caixa",
      status: "ON_TRACK",
      experience: "CRITICAL",
      phase: "AVAILABLE",
      startDate: "2022-05-01",
      expectedDate: "2022-11-01",
      launchDate: "2022-11-15",
      responsible: "Fernanda PO",
      notes: "DEMO — dados desatualizados",
      updatedAt: NOW,
    },
    {
      id: "fcc-cont-area-logada",
      featureId: "feat-resultado-contemplacao",
      productId: "veiculos_pesados",
      channelContextId: "cc-cli-as-area-logada",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2020-08-01",
      expectedDate: "2021-02-01",
      launchDate: "2021-02-10",
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-cont-superapp",
      featureId: "feat-resultado-contemplacao",
      productId: "veiculos_pesados",
      channelContextId: "cc-cli-as-superapp",
      status: "ON_TRACK",
      experience: "NOT_EVALUATED",
      phase: "BACKLOG",
      startDate: "2026-09-01",
      expectedDate: "2027-06-01",
      launchDate: null,
      responsible: "Diana UX",
      notes: "DEMO",
      updatedAt: NOW,
    },

    // --- Segunda via extrato ---
    {
      id: "fcc-ext-app-consorcio",
      featureId: "feat-segunda-via-extrato",
      productId: "veiculos_pesados",
      channelContextId: "cc-cli-as-app-consorcio",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2023-01-01",
      expectedDate: "2023-05-01",
      launchDate: "2023-05-20",
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-ext-area-logada",
      featureId: "feat-segunda-via-extrato",
      productId: "veiculos_pesados",
      channelContextId: "cc-cli-as-area-logada",
      status: "ON_TRACK",
      experience: "GOOD",
      phase: "AVAILABLE",
      startDate: "2022-01-01",
      expectedDate: "2022-06-01",
      launchDate: "2022-06-01",
      responsible: "Fernanda PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-ext-app-caixa",
      featureId: "feat-segunda-via-extrato",
      productId: "veiculos_pesados",
      channelContextId: "cc-cli-as-app-caixa",
      status: "ON_TRACK",
      experience: "NOT_EVALUATED",
      phase: "REMOVED",
      startDate: null,
      expectedDate: null,
      launchDate: null,
      responsible: "Fernanda PO",
      notes: "DEMO — não existe no App CAIXA",
      updatedAt: NOW,
    },
    {
      id: "fcc-ext-superapp",
      featureId: "feat-segunda-via-extrato",
      productId: "veiculos_pesados",
      channelContextId: "cc-cli-as-superapp",
      status: "ON_TRACK",
      experience: "NOT_EVALUATED",
      phase: "REMOVED",
      startDate: null,
      expectedDate: null,
      launchDate: null,
      responsible: "Fernanda PO",
      notes: "DEMO — ainda sem definição no SuperApp",
      updatedAt: NOW,
    },

    // --- Consulta assistida (Economiário / Parceiro) ---
    {
      id: "fcc-assist-portal-eco",
      featureId: "feat-consulta-assistida",
      productId: "veiculos_pesados",
      channelContextId: "cc-eco-as-portal",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2019-01-01",
      expectedDate: "2019-08-01",
      launchDate: "2019-08-15",
      responsible: "Iris PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-assist-plataforma",
      featureId: "feat-consulta-assistida",
      productId: "veiculos_pesados",
      channelContextId: "cc-eco-as-plataforma",
      status: "DELAYED",
      experience: "NOT_EVALUATED",
      phase: "HOMOLOGATION",
      startDate: "2025-03-01",
      expectedDate: "2025-09-01",
      launchDate: null,
      responsible: "Iris PO",
      notes: "DEMO",
      updatedAt: NOW,
    },
    {
      id: "fcc-assist-portal-par",
      featureId: "feat-consulta-assistida",
      productId: "veiculos_pesados",
      channelContextId: "cc-par-as-portal",
      status: "ON_TRACK",
      experience: "NEEDS_IMPROVEMENT",
      phase: "AVAILABLE",
      startDate: "2020-01-01",
      expectedDate: "2020-07-01",
      launchDate: "2020-07-20",
      responsible: "Iris PO",
      notes: "DEMO",
      updatedAt: NOW,
    },

    // --- Novas features por linha de produto ---
    {
      id: "fcc-sim-auto-autocompra",
      featureId: "feat-simular",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-sale-autocompra",
      status: "ON_TRACK",
      experience: "GOOD",
      phase: "AVAILABLE",
      startDate: "2024-02-01",
      expectedDate: "2024-05-01",
      launchDate: "2024-05-15",
      responsible: "Carla PO",
      notes: "DEMO — veículos leves",
      updatedAt: NOW,
    },
    {
      id: "fcc-sim-auto-superapp",
      featureId: "feat-simular",
      productId: "veiculos_leves",
      channelContextId: "cc-cli-sale-superapp",
      status: "ON_TRACK",
      experience: "NOT_EVALUATED",
      phase: "UX_UI",
      startDate: "2026-07-01",
      expectedDate: "2027-01-01",
      launchDate: null,
      responsible: "Ana UX",
      notes: "DEMO — veículos leves",
      updatedAt: NOW,
    },
    {
      id: "fcc-sim-pes-aic",
      featureId: "feat-simular",
      productId: "veiculos_pesados",
      channelContextId: "cc-eco-sale-aic",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2023-01-01",
      expectedDate: "2023-06-01",
      launchDate: "2023-06-20",
      responsible: "Iris PO",
      notes: "DEMO — veículos pesados",
      updatedAt: NOW,
    },
    {
      id: "fcc-sim-pes-plataforma",
      featureId: "feat-simular",
      productId: "veiculos_pesados",
      channelContextId: "cc-eco-sale-plataforma",
      status: "DELAYED",
      experience: "NOT_EVALUATED",
      phase: "DEVELOPMENT",
      startDate: "2025-08-01",
      expectedDate: "2026-03-01",
      launchDate: null,
      responsible: "Carla PO",
      notes: "DEMO — veículos pesados",
      updatedAt: NOW,
    },
    {
      id: "fcc-cota-imob-app",
      featureId: "feat-consultar-cota",
      productId: "imobiliario",
      channelContextId: "cc-cli-as-app-consorcio",
      status: "ON_TRACK",
      experience: "GOOD",
      phase: "AVAILABLE",
      startDate: "2023-03-01",
      expectedDate: "2023-08-01",
      launchDate: "2023-08-15",
      responsible: "Fernanda PO",
      notes: "DEMO — imobiliário",
      updatedAt: NOW,
    },
    {
      id: "fcc-cota-imob-area",
      featureId: "feat-consultar-cota",
      productId: "imobiliario",
      channelContextId: "cc-cli-as-area-logada",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2022-04-01",
      expectedDate: "2022-09-01",
      launchDate: "2022-09-10",
      responsible: "Fernanda PO",
      notes: "DEMO — imobiliário",
      updatedAt: NOW,
    },
    {
      id: "fcc-bol-imob-app",
      featureId: "feat-emitir-boleto",
      productId: "imobiliario",
      channelContextId: "cc-cli-as-app-consorcio",
      status: "ON_TRACK",
      experience: "ADEQUATE",
      phase: "AVAILABLE",
      startDate: "2023-05-01",
      expectedDate: "2023-09-01",
      launchDate: "2023-09-20",
      responsible: "Fernanda PO",
      notes: "DEMO — imobiliário",
      updatedAt: NOW,
    },
    {
      id: "fcc-bol-imob-superapp",
      featureId: "feat-emitir-boleto",
      productId: "imobiliario",
      channelContextId: "cc-cli-as-superapp",
      status: "ON_TRACK",
      experience: "NOT_EVALUATED",
      phase: "BACKLOG",
      startDate: "2026-09-01",
      expectedDate: "2027-03-01",
      launchDate: null,
      responsible: "Diana UX",
      notes: "DEMO — imobiliário",
      updatedAt: NOW,
    },
  ],

  evidences: [
    {
      id: "ev-1",
      featureId: "feat-dar-lance",
      title: "Reclamações sobre erro ao ofertar lance",
      type: "COMPLAINT",
      description:
        "[DEMO] Volume elevado de reclamações na Área logada sobre validação de lance.",
      link: null,
      date: "2026-07-10",
      filePath: null,
      fileName: null,
      fileMime: null,
      fileSize: null,
      responsible: "Eduardo CX",
    },
    {
      id: "ev-2",
      featureId: "feat-consultar-cota",
      title: "Pesquisa de usabilidade App Consórcio",
      type: "UX_RESEARCH",
      description:
        "[DEMO] 12 participantes avaliaram a consulta de cota como clara e rápida.",
      link: null,
      date: "2026-05-20",
      filePath: null,
      fileName: null,
      fileMime: null,
      fileSize: null,
      responsible: "Diana UX",
    },
    {
      id: "ev-3",
      featureId: "feat-resultado-contemplacao",
      title: "Analytics — abandono na tela de contemplação",
      type: "ANALYTICS",
      description:
        "[DEMO] Taxa alta de saída rápida no App CAIXA após abrir contemplação.",
      link: null,
      date: "2026-08-01",
      filePath: null,
      fileName: null,
      fileMime: null,
      fileSize: null,
      responsible: "Bruno CX",
    },
    {
      id: "ev-4",
      featureId: "feat-simular",
      title: "Benchmark de simuladores digitais",
      type: "BENCHMARK",
      description:
        "[DEMO] Comparativo com 4 players do mercado de consórcio.",
      link: null,
      date: "2026-04-12",
      filePath: null,
      fileName: null,
      fileMime: null,
      fileSize: null,
      responsible: "Ana UX",
    },
  ],

  roadmapPhases: [
    {
      id: "rph-backlog",
      code: "BACKLOG",
      name: "Backlog",
      symbol: "◌",
      sortOrder: 1,
      active: false,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-ux-ui",
      code: "UX_UI",
      name: "UX/UI",
      symbol: "◐",
      sortOrder: 2,
      active: false,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-dev",
      code: "DEVELOPMENT",
      name: "Em desenvolvimento",
      symbol: "◐",
      sortOrder: 3,
      active: false,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-homolog",
      code: "HOMOLOGATION",
      name: "Homologação",
      symbol: "◐",
      sortOrder: 4,
      active: false,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-paused",
      code: "PAUSED",
      name: "Pausado",
      symbol: "Ⅱ",
      sortOrder: 5,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-removed",
      code: "REMOVED",
      name: "Removido",
      symbol: "",
      sortOrder: 6,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "rph-available",
      code: "AVAILABLE",
      name: "Disponível",
      symbol: "●",
      sortOrder: 7,
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],

  roadmapItems: [
    {
      id: "rm-1",
      featureId: "feat-consultar-cota",
      channelContextId: "cc-cli-as-superapp",
      phase: "BACKLOG",
      startDate: "2026-09-01",
      expectedDate: "2026-10-15",
      actualDate: null,
      responsible: "Fernanda PO",
      notes: "DEMO — definição de escopo MVP SuperApp",
    },
    {
      id: "rm-2",
      featureId: "feat-dar-lance",
      channelContextId: "cc-cli-as-superapp",
      phase: "DEVELOPMENT",
      startDate: "2026-07-01",
      expectedDate: "2027-01-15",
      actualDate: null,
      responsible: "Fernanda PO",
      notes: "DEMO",
    },
    {
      id: "rm-3",
      featureId: "feat-simular",
      channelContextId: "cc-eco-sale-plataforma",
      phase: "DEVELOPMENT",
      startDate: "2026-05-01",
      expectedDate: "2026-12-01",
      actualDate: null,
      responsible: "Iris PO",
      notes: "DEMO",
    },
    {
      id: "rm-4",
      featureId: "feat-consulta-assistida",
      channelContextId: "cc-eco-as-plataforma",
      phase: "HOMOLOGATION",
      startDate: "2026-03-01",
      expectedDate: "2026-11-01",
      actualDate: null,
      responsible: "Iris PO",
      notes: "DEMO",
    },
  ],

  gaps: [
    {
      id: "gap-1",
      title: "Lance indisponível no App CAIXA",
      description:
        "[DEMO] Cliente consegue dar lance no App Consórcio e na Área logada, mas não no App CAIXA.",
      type: "COVERAGE",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      journeyId: "jrn-lance",
      userNeedId: "need-lance",
      featureId: "feat-dar-lance",
      productId: "veiculos_leves",
      currentChannelId: "ch-app-caixa",
      futureChannelId: "ch-superapp",
      impact: "HIGH",
      priority: "HIGH",
      evidenceIds: ["ev-1"],
      responsible: "Fernanda PO",
      status: "OPEN",
      actionPlan: "Priorizar lance no SuperApp; avaliar hotfix no App CAIXA.",
      isDemo: true,
    },
    {
      id: "gap-2",
      title: "Experiência crítica ao ofertar lance na Área logada",
      description:
        "[DEMO] Funcionalidade disponível, porém com erros frequentes de validação.",
      type: "EXPERIENCE",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      journeyId: "jrn-lance",
      userNeedId: "need-lance",
      featureId: "feat-dar-lance",
      productId: "veiculos_leves",
      currentChannelId: "ch-area-logada",
      futureChannelId: "ch-superapp",
      impact: "CRITICAL",
      priority: "CRITICAL",
      evidenceIds: ["ev-1"],
      responsible: "Diana UX",
      status: "IN_PROGRESS",
      actionPlan: "Redesenhar validações e feedback de erro.",
      isDemo: true,
    },
    {
      id: "gap-3",
      title: "Contemplação inconsistente entre App Consórcio e App CAIXA",
      description:
        "[DEMO] Mesma funcionalidade com qualidade muito diferente entre canais.",
      type: "CONSISTENCY",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      journeyId: "jrn-contemplacao",
      userNeedId: "need-contemplacao",
      featureId: "feat-resultado-contemplacao",
      productId: "veiculos_pesados",
      currentChannelId: "ch-app-caixa",
      futureChannelId: "ch-superapp",
      impact: "HIGH",
      priority: "HIGH",
      evidenceIds: ["ev-3"],
      responsible: "Eduardo CX",
      status: "OPEN",
      actionPlan: "Alinhar fonte de dados e UX padrão no SuperApp.",
      isDemo: true,
    },
    {
      id: "gap-4",
      title: "Extrato sem definição no SuperApp",
      description:
        "[DEMO] Segunda via de extrato existe hoje, mas ainda não tem solução definida no canal futuro.",
      type: "TRANSITION",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      journeyId: "jrn-acompanhamento",
      userNeedId: "need-pagar",
      featureId: "feat-segunda-via-extrato",
      productId: "veiculos_pesados",
      currentChannelId: "ch-app-consorcio",
      futureChannelId: "ch-superapp",
      impact: "MEDIUM",
      priority: "MEDIUM",
      evidenceIds: [],
      responsible: "Fernanda PO",
      status: "OPEN",
      actionPlan: "Incluir no backlog de discovery do SuperApp.",
      isDemo: true,
    },
    {
      id: "gap-5",
      title: "Simulação para Parceiro ainda só no AIC Extrarede",
      description:
        "[DEMO] Portal do Consórcio (futuro para Venda Parceiro) ainda não cobre simulação.",
      type: "TRANSITION",
      audienceId: "aud-partner",
      momentId: "mom-sale",
      journeyId: "jrn-contratacao",
      userNeedId: "need-simular",
      featureId: "feat-simular",
      productId: "imobiliario",
      currentChannelId: "ch-aic-extrarede",
      futureChannelId: "ch-portal",
      impact: "HIGH",
      priority: "HIGH",
      evidenceIds: ["ev-4"],
      responsible: "Iris PO",
      status: "OPEN",
      actionPlan: "Planejar evolução do Portal para venda parceiro.",
      isDemo: true,
    },
    {
      id: "gap-6",
      title: "Utilização do crédito imobiliário sem acompanhamento no Portal",
      description:
        "[DEMO] Cliente imobiliário não consegue acompanhar etapas de compra, construção e reforma.",
      type: "COVERAGE",
      audienceId: "aud-client",
      momentId: "mom-after-sale",
      journeyId: "jrn-acompanhamento",
      userNeedId: "need-acompanhar-cota",
      featureId: null,
      productId: "imobiliario",
      currentChannelId: "ch-portal",
      futureChannelId: "ch-superapp",
      impact: "HIGH",
      priority: "HIGH",
      evidenceIds: [],
      responsible: "Fernanda PO",
      status: "OPEN",
      actionPlan: "Criar funcionalidade de acompanhamento da utilização do crédito.",
      isDemo: true,
    },
  ],

  featureEvolutions: [
    {
      id: "fevo-prod-autocompra-redesenho",
      featureChannelContextId: "fcc-prod-autocompra",
      title: "Melhorar experiência de consulta de produtos",
      description:
        "Redesenho da experiência de consulta para reduzir fricção e aumentar conversão.",
      phase: "DEVELOPMENT",
      status: "IN_PROGRESS",
      priority: "HIGH",
      startDate: "2026-08-01",
      expectedDate: "2026-11-15",
      completedDate: null,
      responsible: "Carla PO",
      notes: "DEMO — Autocompra · Veículos Leves",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "fevo-sim-ibc-acessibilidade",
      featureChannelContextId: "fcc-sim-ibc",
      title: "Acessibilidade na simulação IBC",
      description:
        "Adequação WCAG e leitura de tela no fluxo de simulação.",
      phase: "DEVELOPMENT",
      status: "IN_PROGRESS",
      priority: "MEDIUM",
      startDate: "2026-07-01",
      expectedDate: "2026-10-30",
      completedDate: null,
      responsible: "Carla PO",
      notes: "DEMO",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
    {
      id: "fevo-cota-historico",
      featureChannelContextId: "fcc-cota-area-logada",
      title: "Histórico de consultas da cota",
      description: "Exibir histórico recente de consultas na área logada.",
      phase: "HOMOLOGATION",
      status: "DONE",
      priority: "LOW",
      startDate: "2025-01-10",
      expectedDate: "2025-04-01",
      completedDate: "2025-03-28",
      responsible: "Carla PO",
      notes: "DEMO — concluída",
      active: true,
      createdAt: EARLIER,
      updatedAt: NOW,
    },
  ],
};
