-- Unifica status e fase no mesmo catálogo (feature_channel_contexts + roadmap_items).
-- Status legado → novo status/fase.

UPDATE feature_channel_contexts
SET
  status = CASE status
    WHEN 'PLANNED' THEN 'BACKLOG'
    WHEN 'DISCOVERY' THEN 'BACKLOG'
    WHEN 'DESIGN' THEN 'UX_UI'
    WHEN 'VALIDATION' THEN 'UX_UI'
    WHEN 'PROBLEM' THEN 'AVAILABLE'
    WHEN 'NOT_AVAILABLE' THEN 'REMOVED'
    WHEN 'DISCONTINUED' THEN 'REMOVED'
    ELSE status
  END,
  phase = CASE COALESCE(NULLIF(phase, ''), status)
    WHEN 'NEED_IDENTIFIED' THEN 'BACKLOG'
    WHEN 'DISCOVERY' THEN 'BACKLOG'
    WHEN 'PRIORITIZATION' THEN 'BACKLOG'
    WHEN 'PLANNED' THEN 'BACKLOG'
    WHEN 'UX' THEN 'UX_UI'
    WHEN 'DESIGN' THEN 'UX_UI'
    WHEN 'VALIDATION' THEN 'UX_UI'
    WHEN 'GO_LIVE' THEN 'AVAILABLE'
    WHEN 'POST_GO_LIVE' THEN 'AVAILABLE'
    WHEN 'PROBLEM' THEN 'AVAILABLE'
    WHEN 'NOT_AVAILABLE' THEN 'REMOVED'
    WHEN 'DISCONTINUED' THEN 'REMOVED'
    WHEN 'DEVELOPMENT' THEN 'DEVELOPMENT'
    WHEN 'HOMOLOGATION' THEN 'HOMOLOGATION'
    WHEN 'AVAILABLE' THEN 'AVAILABLE'
    WHEN 'BACKLOG' THEN 'BACKLOG'
    WHEN 'UX_UI' THEN 'UX_UI'
    WHEN 'PAUSED' THEN 'PAUSED'
    WHEN 'REMOVED' THEN 'REMOVED'
    ELSE 'BACKLOG'
  END;

-- Garante status = phase após normalização
UPDATE feature_channel_contexts
SET status = phase
WHERE status IS DISTINCT FROM phase;

UPDATE roadmap_items
SET phase = CASE phase
  WHEN 'NEED_IDENTIFIED' THEN 'BACKLOG'
  WHEN 'DISCOVERY' THEN 'BACKLOG'
  WHEN 'PRIORITIZATION' THEN 'BACKLOG'
  WHEN 'PLANNED' THEN 'BACKLOG'
  WHEN 'UX' THEN 'UX_UI'
  WHEN 'DESIGN' THEN 'UX_UI'
  WHEN 'VALIDATION' THEN 'UX_UI'
  WHEN 'GO_LIVE' THEN 'AVAILABLE'
  WHEN 'POST_GO_LIVE' THEN 'AVAILABLE'
  WHEN 'PROBLEM' THEN 'AVAILABLE'
  WHEN 'NOT_AVAILABLE' THEN 'REMOVED'
  WHEN 'DISCONTINUED' THEN 'REMOVED'
  ELSE phase
END;
